services:
  servarr-exporter:
    image: ghcr.io/onedr0p/servarr_exporter
    container_name: servarr_exporter
    ports:
      - "9707:9707"
    environment:
      - TZ=Pacific/Auckland
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_URL=${RADARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - PROWLARR_URL=${PROWLARR_URL}
      # Add whichever apps you run
    restart: unless-stopped

  snmp_exporter:
    image: prom/snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./config/snmp.yml:/etc/snmp_exporter/snmp.yml

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning 
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

